title: radioshiny.github.io
description: Shinyoung Kim's CV, docs, and code repositories.
remote_theme: just-the-docs/just-the-docs

url: https://radioshiny.github.io

# Color scheme supports "light" (default) and "dark"
color_scheme: shiny

back_to_top: true
back_to_top_text: "Back to top"

search_enabled: true

enable_copy_code_button: true

heading_anchor: true
