title: Shinyoung Kim
description: Shinyoung Kim's CV, docs, and code repositories.
remote_theme: just-the-docs

url: https://radioshiny.github.io

# Color scheme supports "light" (default) and "dark"
color_scheme: light



